---
language: node_js
node_js:
  - 10
  - 11
dist: trusty
sudo: false
install: npm install
before_script:
  - jsvu --os=linux64 --engines=xs
  - 'export PATH="${HOME}/.jsvu:${PATH}"'
script: npm test
